var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/ad-campaign/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__97f10690._.js")
R.c("server/chunks/ssr/_6139f1ce._.js")
R.c("server/chunks/ssr/_0483389e._.js")
R.c("server/chunks/ssr/[root-of-the-server]__61c34455._.js")
R.c("server/chunks/ssr/node_modules_722875e3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_6607e1c8._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__90fb571e._.js")
R.c("server/chunks/ssr/app_loading_tsx_b05711b0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/app_dashboard_layout_tsx_12b56d5a._.js")
R.c("server/chunks/ssr/_next-internal_server_app_dashboard_ad-campaign_page_actions_cdd4c8b9.js")
R.m(59398)
module.exports=R.m(59398).exports
