const { JOB_TYPES, QUEUES } = require('./jobTypes');

const QUEUE_TOPOLOGY = Object.freeze({
    [QUEUES.MAIN]: [
        JOB_TYPES.ADS_MAINTENANCE_SWEEP,
        JOB_TYPES.MEDIA_COMPRESSION_REQUESTED,
        JOB_TYPES.NOTIFICATION_FANOUT_REQUESTED,
        JOB_TYPES.REPORT_GENERATION_REQUESTED,
        JOB_TYPES.SUBSCRIPTION_RENEWAL_SWEEP,
    ],
});

module.exports = {
    QUEUE_TOPOLOGY,
};
