var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/categories/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__a04fb15f._.js")
R.c("server/chunks/ssr/_6139f1ce._.js")
R.c("server/chunks/ssr/_0b8f0fc5._.js")
R.c("server/chunks/ssr/[root-of-the-server]__61c34455._.js")
R.c("server/chunks/ssr/node_modules_722875e3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_6607e1c8._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__90fb571e._.js")
R.c("server/chunks/ssr/app_loading_tsx_b05711b0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/app_dashboard_layout_tsx_12b56d5a._.js")
R.c("server/chunks/ssr/_next-internal_server_app_dashboard_categories_page_actions_9fa99c47.js")
R.m(88265)
module.exports=R.m(88265).exports
