var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/share/[shareCode]/[resellerRef]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__80e1d4e7._.js")
R.c("server/chunks/ssr/_6139f1ce._.js")
R.c("server/chunks/ssr/_acd41075._.js")
R.c("server/chunks/ssr/[root-of-the-server]__61c34455._.js")
R.c("server/chunks/ssr/node_modules_722875e3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_6607e1c8._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__90fb571e._.js")
R.c("server/chunks/ssr/app_loading_tsx_b05711b0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_share_[shareCode]_[resellerRef]_page_actions_1751631a.js")
R.m(37963)
module.exports=R.m(37963).exports
