var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/wallet/topup/bank-transfer/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__bdd12a95._.js")
R.c("server/chunks/ssr/_6139f1ce._.js")
R.c("server/chunks/ssr/_9dc00a50._.js")
R.c("server/chunks/ssr/[root-of-the-server]__61c34455._.js")
R.c("server/chunks/ssr/node_modules_722875e3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_6607e1c8._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__90fb571e._.js")
R.c("server/chunks/ssr/app_loading_tsx_b05711b0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_wallet_topup_bank-transfer_page_actions_78bcc0a6.js")
R.m(37366)
module.exports=R.m(37366).exports
