// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/[username]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[username]">> = Specific
  const handler = {} as typeof import("../../app/[username]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ad-campaign/flash-content/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ad-campaign/flash-content">> = Specific
  const handler = {} as typeof import("../../app/ad-campaign/flash-content/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ad-campaign/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ad-campaign">> = Specific
  const handler = {} as typeof import("../../app/ad-campaign/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ad-campaign/photo-video/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ad-campaign/photo-video">> = Specific
  const handler = {} as typeof import("../../app/ad-campaign/photo-video/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ad-campaign/product-promote/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ad-campaign/product-promote">> = Specific
  const handler = {} as typeof import("../../app/ad-campaign/product-promote/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ad-campaign/profile-promote/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ad-campaign/profile-promote">> = Specific
  const handler = {} as typeof import("../../app/ad-campaign/profile-promote/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ad-campaign/upload-content/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ad-campaign/upload-content">> = Specific
  const handler = {} as typeof import("../../app/ad-campaign/upload-content/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/chats/[username]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chats/[username]">> = Specific
  const handler = {} as typeof import("../../app/chats/[username]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/chats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chats">> = Specific
  const handler = {} as typeof import("../../app/chats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/ad-campaign/flash-content/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/ad-campaign/flash-content">> = Specific
  const handler = {} as typeof import("../../app/dashboard/ad-campaign/flash-content/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/ad-campaign/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/ad-campaign">> = Specific
  const handler = {} as typeof import("../../app/dashboard/ad-campaign/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/ad-campaign/photo-video/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/ad-campaign/photo-video">> = Specific
  const handler = {} as typeof import("../../app/dashboard/ad-campaign/photo-video/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/ad-campaign/product-promote/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/ad-campaign/product-promote">> = Specific
  const handler = {} as typeof import("../../app/dashboard/ad-campaign/product-promote/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/ad-campaign/profile-promote/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/ad-campaign/profile-promote">> = Specific
  const handler = {} as typeof import("../../app/dashboard/ad-campaign/profile-promote/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/ad-campaign/upload-content/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/ad-campaign/upload-content">> = Specific
  const handler = {} as typeof import("../../app/dashboard/ad-campaign/upload-content/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/admin/ads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/ads">> = Specific
  const handler = {} as typeof import("../../app/dashboard/admin/ads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/admin/subscription/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/subscription">> = Specific
  const handler = {} as typeof import("../../app/dashboard/admin/subscription/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/admin/verification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/verification">> = Specific
  const handler = {} as typeof import("../../app/dashboard/admin/verification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/categories">> = Specific
  const handler = {} as typeof import("../../app/dashboard/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/chats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/chats">> = Specific
  const handler = {} as typeof import("../../app/dashboard/chats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/googs/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/googs/[id]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/googs/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/profile">> = Specific
  const handler = {} as typeof import("../../app/dashboard/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/shop/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/shop/[id]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/shop/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/shop/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/shop">> = Specific
  const handler = {} as typeof import("../../app/dashboard/shop/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/support">> = Specific
  const handler = {} as typeof import("../../app/dashboard/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/terms">> = Specific
  const handler = {} as typeof import("../../app/dashboard/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/wallet/ad-center/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/wallet/ad-center">> = Specific
  const handler = {} as typeof import("../../app/dashboard/wallet/ad-center/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/wallet/coins-management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/wallet/coins-management">> = Specific
  const handler = {} as typeof import("../../app/dashboard/wallet/coins-management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/wallet/my-wallet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/wallet/my-wallet">> = Specific
  const handler = {} as typeof import("../../app/dashboard/wallet/my-wallet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/wallet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/wallet">> = Specific
  const handler = {} as typeof import("../../app/dashboard/wallet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/wallet/request/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/wallet/request">> = Specific
  const handler = {} as typeof import("../../app/dashboard/wallet/request/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/wallet/sell/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/wallet/sell">> = Specific
  const handler = {} as typeof import("../../app/dashboard/wallet/sell/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/wallet/subscription/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/wallet/subscription">> = Specific
  const handler = {} as typeof import("../../app/dashboard/wallet/subscription/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/wallet/topup/bank-transfer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/wallet/topup/bank-transfer">> = Specific
  const handler = {} as typeof import("../../app/dashboard/wallet/topup/bank-transfer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/wallet/topup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/wallet/topup">> = Specific
  const handler = {} as typeof import("../../app/dashboard/wallet/topup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/wallet/transactions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/wallet/transactions">> = Specific
  const handler = {} as typeof import("../../app/dashboard/wallet/transactions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/wallet/verification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/wallet/verification">> = Specific
  const handler = {} as typeof import("../../app/dashboard/wallet/verification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/wallet/withdrawal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/wallet/withdrawal">> = Specific
  const handler = {} as typeof import("../../app/dashboard/wallet/withdrawal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/help-support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/help-support">> = Specific
  const handler = {} as typeof import("../../app/help-support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/home/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/home">> = Specific
  const handler = {} as typeof import("../../app/home/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/privacy-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy-policy">> = Specific
  const handler = {} as typeof import("../../app/privacy-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/product/[shareCode]/[resellerRef]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/product/[shareCode]/[resellerRef]">> = Specific
  const handler = {} as typeof import("../../app/product/[shareCode]/[resellerRef]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/product/[shareCode]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/product/[shareCode]">> = Specific
  const handler = {} as typeof import("../../app/product/[shareCode]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/profile/[user]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile/[user]">> = Specific
  const handler = {} as typeof import("../../app/profile/[user]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reel/[shareCode]/[resellerRef]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reel/[shareCode]/[resellerRef]">> = Specific
  const handler = {} as typeof import("../../app/reel/[shareCode]/[resellerRef]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reel/[shareCode]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reel/[shareCode]">> = Specific
  const handler = {} as typeof import("../../app/reel/[shareCode]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/change-login-email/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/change-login-email">> = Specific
  const handler = {} as typeof import("../../app/settings/change-login-email/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/passkeys/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/passkeys">> = Specific
  const handler = {} as typeof import("../../app/settings/passkeys/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/reset-password">> = Specific
  const handler = {} as typeof import("../../app/settings/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/security-alerts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/security-alerts">> = Specific
  const handler = {} as typeof import("../../app/settings/security-alerts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/trusted-devices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/trusted-devices">> = Specific
  const handler = {} as typeof import("../../app/settings/trusted-devices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/two-factor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/two-factor">> = Specific
  const handler = {} as typeof import("../../app/settings/two-factor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/share/[shareCode]/[resellerRef]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/share/[shareCode]/[resellerRef]">> = Specific
  const handler = {} as typeof import("../../app/share/[shareCode]/[resellerRef]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/share/[shareCode]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/share/[shareCode]">> = Specific
  const handler = {} as typeof import("../../app/share/[shareCode]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/share/ad/[adId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/share/ad/[adId]">> = Specific
  const handler = {} as typeof import("../../app/share/ad/[adId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/share/goog/[postId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/share/goog/[postId]">> = Specific
  const handler = {} as typeof import("../../app/share/goog/[postId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/share/product/[shareCode]/[resellerRef]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/share/product/[shareCode]/[resellerRef]">> = Specific
  const handler = {} as typeof import("../../app/share/product/[shareCode]/[resellerRef]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/share/product/[shareCode]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/share/product/[shareCode]">> = Specific
  const handler = {} as typeof import("../../app/share/product/[shareCode]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/shop/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop">> = Specific
  const handler = {} as typeof import("../../app/shop/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/suspended/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/suspended">> = Specific
  const handler = {} as typeof import("../../app/suspended/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/terms-and-conditions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms-and-conditions">> = Specific
  const handler = {} as typeof import("../../app/terms-and-conditions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/terms-and-policies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms-and-policies">> = Specific
  const handler = {} as typeof import("../../app/terms-and-policies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/u/[username]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/u/[username]">> = Specific
  const handler = {} as typeof import("../../app/u/[username]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/wallet-pay/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wallet-pay">> = Specific
  const handler = {} as typeof import("../../app/wallet-pay/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/wallet/ad-center/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wallet/ad-center">> = Specific
  const handler = {} as typeof import("../../app/wallet/ad-center/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/wallet/coins-management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wallet/coins-management">> = Specific
  const handler = {} as typeof import("../../app/wallet/coins-management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/wallet/my-wallet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wallet/my-wallet">> = Specific
  const handler = {} as typeof import("../../app/wallet/my-wallet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/wallet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wallet">> = Specific
  const handler = {} as typeof import("../../app/wallet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/wallet/request/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wallet/request">> = Specific
  const handler = {} as typeof import("../../app/wallet/request/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/wallet/sell/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wallet/sell">> = Specific
  const handler = {} as typeof import("../../app/wallet/sell/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/wallet/subscription/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wallet/subscription">> = Specific
  const handler = {} as typeof import("../../app/wallet/subscription/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/wallet/topup/bank-transfer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wallet/topup/bank-transfer">> = Specific
  const handler = {} as typeof import("../../app/wallet/topup/bank-transfer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/wallet/topup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wallet/topup">> = Specific
  const handler = {} as typeof import("../../app/wallet/topup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/wallet/transactions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wallet/transactions">> = Specific
  const handler = {} as typeof import("../../app/wallet/transactions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/wallet/verification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wallet/verification">> = Specific
  const handler = {} as typeof import("../../app/wallet/verification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/wallet/withdrawal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wallet/withdrawal">> = Specific
  const handler = {} as typeof import("../../app/wallet/withdrawal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/country-codes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/country-codes">> = Specific
  const handler = {} as typeof import("../../app/api/country-codes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/viewer-country/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/viewer-country">> = Specific
  const handler = {} as typeof import("../../app/api/viewer-country/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/country-codes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/country-codes">> = Specific
  const handler = {} as typeof import("../../app/country-codes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/device-location/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/device-location">> = Specific
  const handler = {} as typeof import("../../app/device-location/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/ad-campaign/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/ad-campaign">> = Specific
  const handler = {} as typeof import("../../app/ad-campaign/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/chats/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/chats">> = Specific
  const handler = {} as typeof import("../../app/dashboard/chats/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/profile/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/profile">> = Specific
  const handler = {} as typeof import("../../app/dashboard/profile/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/wallet/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/wallet">> = Specific
  const handler = {} as typeof import("../../app/dashboard/wallet/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/profile/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../app/profile/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
